services:
    ST\TricksBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        public: true
        tags: ['controller.service_arguments']

    ST\TricksBundle\DataFixtures\TrickAndTrickGroupFixtures:
        tags: [doctrine.fixture.orm]