services:
#    fx_user.example:
#        class: Fx\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Fx\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']