services:

    Fx\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    # Event listener in order to redirect loggedin users
    # trying to access following routes :
    # - fx_user_login
    # - fx_user_registration
    # - fx_user_forgotten_password
    fx.userbundle.eventlister.redirect_user:
        class: Fx\UserBundle\EventListener\RedirectUserListener
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Custom authenticator in order to be able to login with username or email
    fx.userbundle.security.login_form_authenticator:
        class: Fx\UserBundle\Security\LoginFormAuthenticator
        autowire: true

    # Hash the user's password when user entity is persisted or updated
    fx.userbundle.security.hash_password_listener:
        class: Fx\UserBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - {name: doctrine.event_subscriber }